#!/usr/bin/env bash
# This script is displaying from 1 to 20
# Display 4 and then "bad luck from china"
# Display 9 and then "bad luck from japan"
# Display 17 and then "bad luck from Italy"

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
